### ISSUE TITLE
Upload code for PDF to Text extraction to the dev branch

### ISSUE THREAD

**Issue by dg1223** [mir-abir-hossain/real-history-of-Bangladesh#22]
Please make a PR to push this code to the dev branch. You can assign me as the reviewer.

https://colab.research.google.com/drive/1sVN9y5uRR7_jYBJNP4TvSfFwfZoLA5sZ?usp=sharing

If necessary, refer to [CONTRIBUTING.md](https://github.com/mir-abir-hossain/real-history-of-Bangladesh/blob/dev/Task-1-Data-Extraction-Preprocess/CONTRIBUTING.md) on how to push code and make a PR. I suggest pushing the code to a new branch and then make a PR to dev.

**Comment by dg1223** [comment]
@amitsingha Would you be able to work on this issue? I assigned @Irtizaya for this earlier but I think you'd be better to take this on.

@Irtizaya I'll keep #23 assigned to you. We may need to add a feature to extract both ben and eng+ben from each book as two separate files. I'll update the issue description.

**Comment by Irtizaya** [comment]
Yes, it makes more sense for me to work on #23 than just upload the code. I'll separate the files and maybe do some difference checking by the end of the week.

**Comment by dg1223** [comment]
Closinng this issue after mergin #25

**Comment by dg1223** [comment]
Closinng this issue after merging #25
